name = "expenses-tracker"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "expenses-db"
database_id = "930109c1-d8de-4632-bc42-b7e3542351c5"
